export const BRAND = {
  bg: "#0E1116",
  card: "#161B22",
  accent: "#5B7C99",
  headline: "#F2F4F8",
  muted: "#A1A8B3",
} as const;

export const KPI_DATA = [
  {
    label: "Revenue (MTD)",
    value: "£47.2k",
    trend: "+12.4%",
    direction: "up" as const,
    color: "#4ADE80",
    sparklinePath: "M0,20 L5,18 L10,15 L15,17 L20,12 L25,10 L30,8 L35,10 L40,6 L45,4 L50,2",
  },
  {
    label: "Pipeline Value",
    value: "£128k",
    trend: "8 deals",
    direction: "up" as const,
    color: "#60A5FA",
    sparklinePath: "M0,18 L5,16 L10,19 L15,14 L20,12 L25,15 L30,10 L35,8 L40,6 L45,7 L50,4",
  },
  {
    label: "Client NPS",
    value: "72",
    trend: "+4 pts",
    direction: "up" as const,
    color: "#FBBF24",
    sparklinePath: "M0,16 L5,15 L10,14 L15,16 L20,13 L25,11 L30,12 L35,9 L40,7 L45,6 L50,5",
  },
  {
    label: "Ad ROAS",
    value: "3.8x",
    trend: "-0.3",
    direction: "down" as const,
    color: "#A855F7",
    sparklinePath: "M0,6 L5,7 L10,5 L15,8 L20,10 L25,9 L30,12 L35,14 L40,13 L45,16 L50,18",
  },
  {
    label: "TBD",
    value: "—",
    trend: "Placeholder",
    direction: "neutral" as const,
    color: "#5B7C99",
    sparklinePath: "",
    placeholder: true,
  },
  {
    label: "TBD",
    value: "—",
    trend: "Placeholder",
    direction: "neutral" as const,
    color: "#5B7C99",
    sparklinePath: "",
    placeholder: true,
  },
] as const;

export const DASHBOARD_CARDS = [
  {
    title: "Financial performance",
    description: "Revenue, expenses, profit margins, cash flow and burn rate",
    href: "/financial",
    color: "#4ADE80",
    icon: "TrendingUp" as const,
    status: "Live",
  },
  {
    title: "Sales & pipeline",
    description: "Deal flow, conversion rates, pipeline stages and forecasts",
    href: "/sales",
    color: "#60A5FA",
    icon: "BarChart3" as const,
    status: "Live",
  },
  {
    title: "Client success",
    description: "NPS scores, retention, support tickets and health scores",
    href: "/clients",
    color: "#FBBF24",
    icon: "Users" as const,
    status: "Live",
  },
  {
    title: "Meta ads",
    description: "Ad spend, ROAS, CTR, CPL and campaign performance",
    href: "/meta-ads",
    color: "#A855F7",
    icon: "Megaphone" as const,
    status: "Live",
  },
  {
    title: "Dashboard 5",
    description: "Placeholder — coming soon",
    href: "/dashboard-5",
    color: "#5B7C99",
    icon: "LayoutGrid" as const,
    status: "Coming soon",
    placeholder: true,
  },
  {
    title: "Dashboard 6",
    description: "Placeholder — coming soon",
    href: "/dashboard-6",
    color: "#5B7C99",
    icon: "LayoutGrid" as const,
    status: "Coming soon",
    placeholder: true,
  },
] as const;
